### ISSUE TITLE
Better description needed

### ISSUE THREAD

**Issue by CrazyPython** [ppcg/ppcg.github.io#4]
- This site is linked to from chat description. Why is it officially unofficial?
- What does that even mean?
- Why aren't are mods contributors?

**Comment by ararslan** [comment]
The description is intended to be silly. This site is not official in any way nor should its contents be considered official policy.

I'm not sure what you mean about the moderators not being contributors. If you click [Contributors](https://github.com/ppcg/ppcg.github.io/graphs/contributors), you'll see that Doorknob (KeyboardFire), Dennis (DennisMitchell), and myself (Alex A., ararslan) are indeed contributors. Granted, all that means is that we've contributed code to the project. All of the current moderators have provided input on the contents of the site before it was hosted, and a number of folks in The Nineteenth Byte have provided suggestions.
