### ISSUE TITLE
Rickroll Policy?

### ISSUE THREAD

**Issue by vihanb** [ppcg/ppcg.github.io#5]
Rickrolls are not something seen in a productive chatroom. They are especially annoying when:
- You pay per byte
- You are on mobile and do not wish to see a $1000 overage charge from Verizon

While it might be hilarious to see someone watch "Never Gonna Give You Up" when they didn't expect too, the meme is approaching 10 years of age, you've had plenty of time to rickroll your friends (and not-so-friends).

---

Can a policy be added regarding them?

**Comment by ararslan** [comment]
I think that's getting too specific. The point of the chatiquette document is to be a slightly more specific way of saying, "Use common sense and be respectful." It would be difficult and perhaps unfairly restrictive to curate a list of things to ban. Arguably rickrolls fall under the "avoid posting messages that add nothing to the conversation" bullet point anyway.

That said, as was discussed on meta, the document isn't official policy, it's a set of guidelines. If someone is posting a bunch of rickrolls, I think it suffices to politely point out that they're increasing the noise level in the room and distracting from on-topic conversation, and politely request that they stop.
